---
title: "dockerR: an R package for managing docker images & containers"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- 
Run this 'development' chunk

Store every call to library() that you need to run chunks line by line, as in a classical Rmd for analysis
-->

```{r development, include=FALSE}
library(testthat)
```

<!--
# Description of your package

This will fill the description of your package.
Fill and run the content of this chunk, before anything else. 

Note: when you will use other flat templates, this part will be in a separate file. Do not be surprised!
--> 

```{r description, eval=FALSE}
# Describe your package
fusen::fill_description(
  pkg = here::here(),
  overwrite = TRUE,
  fields = list(
    Title = "dockerR",
    Description = "dockerR: an R package for managing docker images & containers.",
    version = "0.1.0",
    `Authors@R` = c(
      person("Yanhua", "Zheng", email = "zyh3084989256@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-1103-9579"))
    )
  )
)
# Define License with use_*_license()
usethis::use_mit_license("YanhuaZheng")

#usethis::use_version("0.1.0","0.1.0.1")
# use packages

usethis::use_pipe()
usethis::use_package("fs")
usethis::use_package("glue")
```

# list the images in the local 


```{r function-lscontainer}
#' Add one to any value
#' 
#' @param base_command A str
#' @param additional A str
#' @param use_podman logit, use podman as  backend when it is TRUE
#'
#' @return data.frame
#' @export

lscontainer <- function(base_command = "docker ps",
                             additional = "-a", use_podman = FALSE){
  
  if (!is.na(additional)){
    commandline <- glue::glue("{base_command} {additional}")
  } else {
    commandline <- base_command
  }
  
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},runing..."))
  output <- system(command = commandline,
                   intern = TRUE)
  header <- output[1]
  data_lines <- output[-1]
  data <- do.call(rbind, lapply(data_lines, function(x) {
    strsplit(x, "\\s{2,}")[[1]]
  }))
  header_clean <- strsplit(header, "\\s{2,}")[[1]]
  if (ncol(data) == length(header_clean)) {
    colnames(data) <- header_clean
    data <- as.data.frame(data)
    return(data)
  }else{
    message("something went wrong, check your command")
    return(NA)
  }
}

```

<!--
Here is an example on how to use the function.
This should be a reproducible and working example
-->

```{r examples-lscontainer}
lscontainer(additional = "-a")
```

<!--
Here are some unit tests to verify the function works as expected.
-->

```{r tests-lscontainer}
test_that("lsimage works", {
  expect_true(inherits(lscontainer, "function")) 
})
```

# lsimage
    
```{r function-lsimage}
#' Title
#' lsimage
#' Description
#' list all images
#' @param base_command the base command 
#' @param additional additional command
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return data.frame
#' 
#' @export
lsimage <- function(base_command = "docker images",
                    additional = NA, use_podman = FALSE){
  
  if (!is.na(additional)){
    commandline <- glue::glue("{base_command} {additional}")
  } else {
    commandline <- base_command
  }
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},runing..."))
  output <- system(command = commandline,
                   intern = TRUE)
  header <- output[1]
  data_lines <- output[-1]
  data <- do.call(rbind, lapply(data_lines, function(x) {
    strsplit(x, "\\s{2,}")[[1]]
  }))
  header_clean <- strsplit(header, "\\s{2,}")[[1]]
  if (ncol(data) == length(header_clean)) {
    colnames(data) <- header_clean
    data <- as.data.frame(data)
    return(data)
  }else{
    message("something went wrong, check your command")
    return(NA)
  }
}

```
  
```{r example-lsimage}
lsimage()
```
  
```{r tests-lsimage}
test_that("lsimage works", {
  expect_true(inherits(lsimage, "function")) 
})
```
  
# docker_stats
    
```{r function-docker_stats}
#' container stats
#' 
#' show the container stats in a data.frame
#' @param base_command the base command 
#' @param additional additional command
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return data.frame
#' 
#' @export
docker_stats <- function(base_command = "docker stats --no-stream",
                    additional = NA, use_podman = FALSE){
  
  if (!is.na(additional)){
    commandline <- glue::glue("{base_command} {additional}")
  } else {
    commandline <- base_command
  }
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},runing..."))
  output <- system(command = commandline,
                   intern = TRUE)
  header <- output[1]
  data_lines <- output[-1]
  data <- do.call(rbind, lapply(data_lines, function(x) {
    strsplit(x, "\\s{2,}")[[1]]
  }))
  header_clean <- strsplit(header, "\\s{2,}")[[1]]
  if (ncol(data) == length(header_clean)) {
    colnames(data) <- header_clean
    data <- as.data.frame(data)
    return(data)
  }else{
    message("something went wrong, check your command")
    return(NA)
  }
}
```
  
```{r example-docker_stats}
docker_stats()
```
  
```{r tests-docker_stats}
test_that("docker_stats works", {
  expect_true(inherits(docker_stats, "function")) 
})
```
  

# image_rmi
    
```{r function-image_rmi}
#' Title
#' image_rmi
#' Description
#' remove images
#' @param id the image id ,str 
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
image_rmi <- function(id, use_podman = FALSE){
    commandline <- glue::glue("docker rmi {id}")
    if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
    message(glue::glue("info\\ your command is {commandline},checking the imageids..."))
    allimage <- lsimage(use_podman = use_podman)
    if (id %in% c(allimage$REPOSITORY,allimage$`IMAGE ID`)){
      system(commandline)
    }else{
      message("the imageid is not correct")
    }
    return(id)
}
```
  
```{r example-image_rmi}
image_rmi("frooodle/s-pdf:latest")
```
  
```{r tests-image_rmi}
test_that("image_rmi works", {
  expect_true(inherits(image_rmi, "function")) 
})
```
  
# image_pull
    
```{r function-image_pull}
#' Title
#' image_pull
#' Description
#' pull image from dockerhub
#' 
#' @param id the image id ,str
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
image_pull <- function(id, use_podman = FALSE){
  commandline <- glue::glue("docker pull {id}")
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},checking the imageids..."))
  allimage <- lsimage(use_podman = use_podman)
  if (id %in% allimage$REPOSITORY){
    message("the image already exist")
  }else{
    system(commandline)
  }
  return(id)
}
```
  
```{r example-image_pull}
image_pull("frooodle/s-pdf:latest")
```
  
```{r tests-image_pull}
test_that("image_pull works", {
  expect_true(inherits(image_pull, "function")) 
})
```

# image_tag
    
```{r function-image_tag}
#' Title
#' image_tag
#' Description
#' change the tag of image
#' @param oldtag the old/original image label,str
#' @param newtag the new image label,str
#' @param .keep whether to keep the oldtag image
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
image_tag <- function(oldtag,newtag,.keep = TRUE, use_podman = FALSE){
  commandline <- glue::glue("docker tag {oldtag} {newtag}")
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},checking the imageids..."))
  allimage <- lsimage(use_podman = use_podman)
  if (oldtag %in% allimage$REPOSITORY){
    system(commandline)
    if (.keep == FALSE){
      image_rmi(oldtag)
    }
    return(newtag)
  }else{
    message("the oldtag does not exist")
    return(oldtag)
  } 
}

```
  
```{r example-image_tag}
  image_tag("diygod/rsshub","fall/rsshub")
```
  
```{r tests-image_tag}
test_that("image_tag works", {
  expect_true(inherits(image_tag, "function")) 
})
```

# image_build
    
```{r function-image_build}
#' Title
#' image_build
#' Description
#' build docker image from Dockerfile
#' @param name the label of the built image
#' @param folder_dockerfile the dir where the dockerfile lies in 
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
image_build <- function(name,folder_dockerfile, use_podman = FALSE){
  if(dir.exists(folder_dockerfile)){
    commandline <- glue::glue("docker build -t {name} {folder_dockerfile}")
    if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
    dockerfile <- glue::glue("{folder_dockerfile}/Dockerfile")
    message(glue::glue("info\\ your command is {commandline},checking the Dockerfile..."))
    if (file.exists(dockerfile)){
      system(commandline)
      return(name)
    } else {
      message("Dockerfile not found")
    }
  }else {
    message("the folder of Dockerfile not found")
  }
}

```
  
```{r example-image_build}
image_build("fallingstar10/gmadeomicsrocker:base","./dev/gmade_rocker-base")
```
  
```{r tests-image_build}
test_that("image_build works", {
  expect_true(inherits(image_build, "function")) 
})
```
# image_push
    
```{r function-image_push}
#' Title
#' image_push
#' Description
#' push image to dockerhub
#' @param containername the label of the pushed image
#' @param username the username of dockerhub account
#' @param password the password of dockerhub account
#' @param auther if the a dockerhub account has previously login,then auther should be FALSE
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
image_push <- function(containername,username = "example",password = "example",auther = FALSE, use_podman = FALSE){
  message("info\\this function will push your image to dockerhub")
  if (auther == FALSE){
    dockerlogin <- ""
  } else {
    dockerlogin <- glue::glue("docker login -u {username} -p {password}")
    if (use_podman) {
    dockerlogin = stringr::str_replace(dockerlogin,"docker","podman")
  }
  }
  dockerpush <- glue::glue("docker push {containername}")
  if (use_podman) {
    dockerpush = stringr::str_replace(dockerpush,"docker","podman")
  }
  if (grepl(username,containername)){
    if (auther == FALSE){
      system(dockerpush)
      } else {
        system(dockerlogin)
        system(dockerpush)
        }
    
    return(containername)
  }else {
    message("conflit found in the containername and the username,please re-taging...")
  }
}
```
  
```{r example-image_push}
image_push("fallingstar10/gmadeomicsrocker:base",username = "fallingstar10")
```
  
```{r tests-image_push}
test_that("image_push works", {
  expect_true(inherits(image_push, "function")) 
})
```

# image_save
    
```{r function-image_save}
#' Title
#' image_save
#' Description
#' save image as tarfile
#' @param imageid the image label 
#' @param tarfile the dest output tarfile,with a full dir and its name
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
image_save <- function(imageid,tarfile, use_podman = FALSE){
  # 先判断是不是在列表里
  # docker save -o my_ubuntu_v3.tar runoob/ubuntu:v3
  if (!dir.exists(dirname(tarfile))){
    fs::dir_create(
      dirname(tarfile)
    )
  }
  commandline <- glue::glue("docker save -o {tarfile} {imageid}")
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},checking the imageid..."))
  allimage <- lsimage(use_podman = use_podman)
  if (imageid %in% c(allimage$REPOSITORY,allimage$`IMAGE ID`)){
    system(commandline)
  }else{
    message("the imageid is not correct")
  }
  return(tarfile)
}
```
  
```{r example-image_save}
image_save("diygod/rsshub","./rsshub.tar")
```
  
```{r tests-image_save}
test_that("image_save works", {
  expect_true(inherits(image_save, "function")) 
})
```

# image_load
    
```{r function-image_load}
#' Title
#' image_load
#' Description
#' load tarfile to docker image
#' @param tarfile the dest output tarfile,with a full dir and its name
#' @param import not using "load" command when its true
#' @param imageid the image label 
#' @param use_podman logit, use podman as  backend when it is TRUE
#' 
#' @return str
#' 
#' @export
image_load <- function(tarfile,import = FALSE,imageid = NULL, use_podman = FALSE){
  #docker load --input fedora.tar
  allimage <- lsimage(use_podman = use_podman)
  if (!is.null(imageid) | !(imageid %in% c(allimage$REPOSITORY,allimage$`IMAGE ID`))){
    importvalidation = TRUE
  } else {
    importvalidation = FALSE
  }
  if (file.exists(tarfile)){
    if (import == FALSE){
      system(command = glue::glue("docker load --input {tarfile}"))
      return(tarfile)
    }else if (importvalidation){
      system(command = glue::glue("docker import {tarfile} {imageid}"))
      return(imageid)
    } else {
      message("please input a specific imageid ,which should has no confilct with existed names")
    }
  } else {
    message("tarfile does not exists")
  }
}
```
  
```{r example-image_load}
image_load(tarfile = "./dev/rsshub.tar",import = TRUE,imageid = "rsshub:load")
```
  
```{r tests-image_load}
test_that("image_load works", {
  expect_true(inherits(image_load, "function")) 
})
```

# container_run
    
```{r function-container_run}
#' Title
#' container_run
#' Description
#' run container at the first time
#' @param imageid the image label 
#' @param name the name of the container
#' @param volume the volume setting of the container
#' @param ports the ports setting of the container
#' @param environmentvarible the "-e" options of docker
#' @param ifD the "-d" option of docker
#' @param restart the "--restart=always" option
#' @param run_at_once whether using "create" or "run"
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
container_run <- function(imageid,
                          name,
                          volume = NULL,
                          ports,
                          environmentvarible = NULL,
                          ifD = TRUE, 
                          restart = TRUE,
                          run_at_once = TRUE, use_podman = FALSE){
  if (run_at_once){
    run <- "run"
  } else {
    run <- "create"
  }
  if (restart){
    restart <- "--restart=always"
  } else {
    restart <- ""
  }
  if (ifD){
    ifD <- "-d"
  }else{
    ifD <- ""
  }
  if (is.null(volume)){
    volume <- ""
  }
  if (is.null(environmentvarible)){
    environmentvarible <- ""
  }
  commandline <- glue::glue("docker {run} {ifD} {restart} --name={name} {ports} {volume} {environmentvarible} {imageid}")
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},checking the imageid..."))
  allimage <- lsimage(use_podman = use_podman)
  if (imageid %in% c(allimage$REPOSITORY,allimage$`IMAGE ID`)){
    system(commandline)
  }else{
    message("the imageid is not correct")
  }
  return(name)

} 
```
  
```{r example-container_run}
container_run("diygod/rsshub","rsshubnew",ports = "-p 1300:1200")
```
  
```{r tests-container_run}
test_that("container_run works", {
  expect_true(inherits(container_run, "function")) 
})
```
# container_control
    
```{r function-container_control}
#' Title
#' container_control
#' Description
#' control the statue of containers by stop, start ,restart and delete(rm)
#' 
#' @param containerid the label of container
#' @param mod the control mod,including stop, start ,restart and delete(rm)
#' @param forcerm force remove the container if its true
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
container_control <- function(containerid,mod = c("stop","start","restart","rm"),
                              forcerm = FALSE
, use_podman = FALSE){
  if (mod != "rm"){
    commandline <- glue::glue("docker {mod} {containerid}")
  } else if(forcerm) {
    commandline <- glue::glue(" docker {mod} -f {containerid}")
  } else {
    commandline <- glue::glue(" docker {mod}  {containerid}")
  }
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},checking the containerid..."))
  allcontainer <-lscontainer(use_podman = use_podman)
  if (containerid %in% c( allcontainer$NAMES,allcontainer$`CONTAINER ID`,allcontainer$PORTS)){
    system(commandline)
  }else{
    message("the containerid is not correct")
  }
  return(containerid)
}
```
  
```{r example-container_control}
container_control("rsshubnew","restart")
```
  
```{r tests-container_control}
test_that("container_control works", {
  expect_true(inherits(container_control, "function")) 
})
```
# container_update
    
```{r function-container_update}
#' Title
#' container_update
#' Description
#' update the container when the upstream image changes
#' @param imageid the image label 
#' @param containerid the name of the container
#' @param force_rm_container force remove the container if its true
#' @param volume the volume setting of the container
#' @param ports the ports setting of the container
#' @param environmentvarible the "-e" options of docker
#' @param ifD the "-d" option of docker
#' @param restart the "--restart=always" option
#' @param run_at_once whether using "create" or "run"
#' @param use_podman logit, use podman as  backend when it is TRUE
#' 
#' @return str
#' 
#' @export
container_update <- function(containerid,imageid,
                             force_rm_container = FALSE,
                             volume = NULL,
                             ports,
                             environmentvarible = NULL,
                             ifD = TRUE, 
                             restart = TRUE,
                             run_at_once = TRUE,
                             use_podman = FALSE){
  # stop
  message("stop the container")
  container_control(containerid,"stop",use_podman = use_podman) %>% 
    container_control("rm",forcerm = force_rm_container ,use_podman = use_podman)
  # rm image
  message("deleting the old images and pull a new one")
  image_rmi(imageid,use_podman = use_podman)  %>% 
    image_pull(use_podman = use_podman) 
  # rerunimage
  message("re-run the container")
  container_run(imageid,
                containerid,
                volume,
                ports,
                environmentvarible,
                ifD,
                restart,
                run_at_once,
                use_podman = use_podman)
  return(containerid)
}

```
  
```{r example-container_update}
container_update("rsshubnew","diygod/rsshub",ports = "-p 1300:1200",restart = FALSE)
```
  
```{r tests-container_update}
test_that("container_update works", {
  expect_true(inherits(container_update, "function")) 
})
```

# container_updateparameter
    
```{r function-container_updateparameter}
#' Title
#' container_updateParameter
#' Description
#' update the Parameter during the runing of container
#' @param containerid the name of the container
#' @param updateParameter new parameter used to update the container
#' 
#' @return str
#' 
#' @export
container_updateParameter <- function(containerid,updateParameter){
  commandline <- glue::glue("docker container update {updateParameter} {containerid}")
  message(glue::glue("info\\ your command is {commandline},checking the containerid..."))
  allcontainer <-lscontainer()
  if (containerid %in% c( allcontainer$NAMES,allcontainer$`CONTAINER ID`,allcontainer$PORTS)){
    system(commandline)
  }else{
    message("the containerid is not correct")
  }
  return(containerid)
}
```
  
```{r example-container_updateparameter}
container_updateParameter("rsshubnew","--restart=always")
```
  
```{r tests-container_updateparameter}
test_that("container_updateparameter works", {
  expect_true(inherits(container_updateParameter, "function")) 
})
```

# container_exec
    
```{r function-container_exec}
#' Title
#' container_exec
#' Description
#' run commands inside the container
#' 
#' @param containerid the name of the container
#' @param command commands need to be run inside the container
#' @param use_podman logit, use podman as  backend when it is TRUE
#' 
#' @return str
#' 
#' @export
container_exec <- function(containerid,command, use_podman = FALSE){
  # docker exec -it 9df70f9a0714 /bin/bash
  commandline <- glue::glue("docker exec -it {containerid} /bin/bash {command} ")
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},checking the containerid..."))
  allcontainer <-lscontainer(use_podman = use_podman)
  if (containerid %in% c( allcontainer$NAMES,allcontainer$`CONTAINER ID`,allcontainer$PORTS)){
    system(commandline)
  }else{
    message("the containerid is not correct")
  }
  return(containerid)
}
```
  
```{r example-container_exec}
container_exec("rsshubnew","pwd")
```
  
```{r tests-container_exec}
test_that("container_exec works", {
  expect_true(inherits(container_exec, "function")) 
})
```
# container_dockercompose
    
```{r function-container_dockercompose}
#' Title
#' container_dockercompose
#' Description
#' initial container by docker compose
#' @param yamlfile the docker compose yaml file 
#' @param use_podman logit, use podman as  backend when it is TRUE
#'
#' 
#' @return str
#' 
#' @export
container_dockercompose <- function(yamlfile, use_podman = FALSE){
  if (file.exists(yamlfile)){
    if (use_podman){
      commandline = glue::glue("podman-compose -f {yamlfile} up -d")
    } else {
      commandline = glue::glue("docker-compose -f {yamlfile} up -d")
    }
    system(command = commandline)
  } else {
    message("yamlfile does not exist")
  }
  return(yamlfile)
}
```
  
```{r example-container_dockercompose}
container_dockercompose("./dev/nextcloud_compose.yaml")
```
  
```{r tests-container_dockercompose}
test_that("container_dockercompose works", {
  expect_true(inherits(container_dockercompose, "function")) 
})
```

# docker_info
    
```{r function-docker_info}
#' docker information
#' 
#' display the information of the installed docker
#' 
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
docker_info <- function(use_podman = FALSE){
  if (use_podman) {
     system("podman info")
  }else {
    system("docker info")
  }  
}
```
  
```{r example-docker_info}
docker_info()
```
  
```{r tests-docker_info}
test_that("docker_info works", {
  expect_true(inherits(docker_info, "function")) 
})
```

# docker_version
    
```{r function-docker_version}
#' docker information
#' 
#' display the information of the installed docker
#' 
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
docker_version <- function(use_podman = FALSE){
    if (use_podman) {
     system("podman version")
  }else {
    system("docker version")
  }  
}
```
  
```{r example-docker_version}
docker_version()
```
  
```{r tests-docker_version}
test_that("docker_version works", {
  expect_true(inherits(docker_version, "function")) 
})
```


 
<!-- 
# Inflate your package

You're one inflate from paper to box.
Build your package from this very Rmd using `fusen::inflate()` 
-->


```{r development-inflate, eval=FALSE}
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_first.Rmd")
```

<!-- 
- Verify your `"DESCRIPTION"` file has been updated
- Verify your function is in `"R/"` directory
- Verify your test is in `"tests/testthat/"` directory
- Verify this Rmd appears in `"vignettes/"` directory 
-->
