# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("container_updateparameter works", {
  expect_true(inherits(container_updateParameter, "function")) 
})

test_that("container_exec works", {
  expect_true(inherits(container_exec, "function")) 
})
