# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("image_push works", {
  expect_true(inherits(image_push, "function")) 
})

test_that("image_save works", {
  expect_true(inherits(image_save, "function")) 
})
