# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' container_run
#' Description
#' run container at the first time
#' @param imageid the image label 
#' @param name the name of the container
#' @param volume the volume setting of the container
#' @param ports the ports setting of the container
#' @param environmentvarible the "-e" options of docker
#' @param ifD the "-d" option of docker
#' @param restart the "--restart=always" option
#' @param run_at_once whether using "create" or "run"
#' @return str
#' 
#' @export
#' @examples
#' container_run("diygod/rsshub","rsshubnew",ports = "-p 1300:1200")
container_run <- function(imageid,
                          name,
                          volume = NULL,
                          ports,
                          environmentvarible = NULL,
                          ifD = TRUE, 
                          restart = TRUE,
                          run_at_once = TRUE){
  if (run_at_once){
    run <- "run"
  } else {
    run <- "create"
  }
  if (restart){
    restart <- "--restart=always"
  } else {
    restart <- ""
  }
  if (ifD){
    ifD <- "-d"
  }else{
    ifD <- ""
  }
  if (is.null(volume)){
    volume <- ""
  }
  if (is.null(environmentvarible)){
    environmentvarible <- ""
  }
  commandline <- glue::glue("docker {run} {ifD} {restart} --name={name} {ports} {volume} {environmentvarible} {imageid}")
  message(glue::glue("info\\ your command is {commandline},checking the imageid..."))
  allimage <- lsimage()
  if (imageid %in% c(allimage$REPOSITORY,allimage$`IMAGE ID`)){
    system(commandline)
  }else{
    message("the imageid is not correct")
  }
  return(name)

} 
