# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' container_exec
#' Description
#' run commands inside the container
#' 
#' @param containerid the name of the container
#' @param command commands need to be run inside the container
#' 
#' @return str
#' 
#' @export
#' @examples
#' container_exec("rsshubnew","pwd")
container_exec <- function(containerid,command){
  # docker exec -it 9df70f9a0714 /bin/bash
  commandline <- glue::glue("docker exec -it {containerid} /bin/bash {command} ")
  message(glue::glue("info\\ your command is {commandline},checking the containerid..."))
  allcontainer <-lscontainer()
  if (containerid %in% c( allcontainer$NAMES,allcontainer$`CONTAINER ID`,allcontainer$PORTS)){
    system(commandline)
  }else{
    message("the containerid is not correct")
  }
  return(containerid)
}
