# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' container_dockercompose
#' Description
#' initial container by docker compose
#' @param yamlfile the docker compose yaml file 
#'
#' 
#' @return str
#' 
#' @export
#' @examples
#' container_dockercompose("./dev/nextcloud_compose.yaml")
container_dockercompose <- function(yamlfile){
  if (file.exists(yamlfile)){
    system(command = glue::glue("docker-compose -f {yamlfile} up -d"))
  } else {
    message("yamlfile does not exist")
  }
  return(yamlfile)
}
