# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' container_dockercompose
#' Description
#' initial container by docker compose
#' @param yamlfile the docker compose yaml file 
#' @param use_podman logit, use podman as  backend when it is TRUE
#'
#' 
#' @return str
#' 
#' @export
#' @examples
#' container_dockercompose("./dev/nextcloud_compose.yaml")
container_dockercompose <- function(yamlfile, use_podman = FALSE){
  if (file.exists(yamlfile)){
    if (use_podman){
      commandline = glue::glue("podman-compose -f {yamlfile} up -d")
    } else {
      commandline = glue::glue("docker-compose -f {yamlfile} up -d")
    }
    system(command = commandline)
  } else {
    message("yamlfile does not exist")
  }
  return(yamlfile)
}
