# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' container_update
#' Description
#' update the container when the upstream image changes
#' @param imageid the image label 
#' @param containerid the name of the container
#' @param force_rm_container force remove the container if its true
#' @param volume the volume setting of the container
#' @param ports the ports setting of the container
#' @param environmentvarible the "-e" options of docker
#' @param ifD the "-d" option of docker
#' @param restart the "--restart=always" option
#' @param run_at_once whether using "create" or "run"
#' @param use_podman logit, use podman as  backend when it is TRUE
#' 
#' @return str
#' 
#' @export
#' @examples
#' container_update("rsshubnew","diygod/rsshub",ports = "-p 1300:1200",restart = FALSE)
container_update <- function(containerid,imageid,
                             force_rm_container = FALSE,
                             volume = NULL,
                             ports,
                             environmentvarible = NULL,
                             ifD = TRUE, 
                             restart = TRUE,
                             run_at_once = TRUE,
                             use_podman = FALSE){
  # stop
  message("stop the container")
  container_control(containerid,"stop",use_podman = use_podman) %>% 
    container_control("rm",forcerm = force_rm_container ,use_podman = use_podman)
  # rm image
  message("deleting the old images and pull a new one")
  image_rmi(imageid,use_podman = use_podman)  %>% 
    image_pull(use_podman = use_podman) 
  # rerunimage
  message("re-run the container")
  container_run(imageid,
                containerid,
                volume,
                ports,
                environmentvarible,
                ifD,
                restart,
                run_at_once,
                use_podman = use_podman)
  return(containerid)
}

