# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' container_updateParameter
#' Description
#' update the Parameter during the runing of container
#' @param containerid the name of the container
#' @param updateParameter new parameter used to update the container
#' 
#' @return str
#' 
#' @export
#' @examples
#' container_updateParameter("rsshubnew","--restart=always")
container_updateParameter <- function(containerid,updateParameter){
  commandline <- glue::glue("docker container update {updateParameter} {containerid}")
  message(glue::glue("info\\ your command is {commandline},checking the containerid..."))
  allcontainer <-lscontainer()
  if (containerid %in% c( allcontainer$NAMES,allcontainer$`CONTAINER ID`,allcontainer$PORTS)){
    system(commandline)
  }else{
    message("the containerid is not correct")
  }
  return(containerid)
}
