# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' container_control
#' Description
#' control the statue of containers by stop, start ,restart and delete(rm)
#' 
#' @param containerid the label of container
#' @param mod the control mod,including stop, start ,restart and delete(rm)
#' @param forcerm force remove the container if its true
#' @return str
#' 
#' @export
#' @examples
#' container_control("rsshubnew","restart")
container_control <- function(containerid,mod = c("stop","start","restart","rm"),
                              forcerm = FALSE
){
  if (mod != "rm"){
    commandline <- glue::glue("docker {mod} {containerid}")
  } else if(forcerm) {
    commandline <- glue::glue(" docker {mod} -f {containerid}")
  } else {
    commandline <- glue::glue(" docker {mod}  {containerid}")
  }
  
  message(glue::glue("info\\ your command is {commandline},checking the containerid..."))
  allcontainer <-lscontainer()
  if (containerid %in% c( allcontainer$NAMES,allcontainer$`CONTAINER ID`,allcontainer$PORTS)){
    system(commandline)
  }else{
    message("the containerid is not correct")
  }
  return(containerid)
}
