# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' docker information
#' 
#' display the information of the installed docker
#' 
#' @return str
#' 
#' @export
#' @examples
#' docker_info()
docker_info <- function(){
    system("docker info")
}
