# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' docker information
#' 
#' display the information of the installed docker
#' 
#' @return str
#' 
#' @export
#' @examples
#' docker_version()
docker_version <- function(){
    system("docker version")
}
