# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' image_load
#' Description
#' load tarfile to docker image
#' @param tarfile the dest output tarfile,with a full dir and its name
#' @param import not using "load" command when its true
#' @param imageid the image label 
#' 
#' @return str
#' 
#' @export
#' @examples
#' image_load(tarfile = "./dev/rsshub.tar",import = TRUE,imageid = "rsshub:load")
image_load <- function(tarfile,import = FALSE,imageid = NULL){
  #docker load --input fedora.tar
  allimage <- lsimage()
  if (!is.null(imageid) | !(imageid %in% c(allimage$REPOSITORY,allimage$`IMAGE ID`))){
    importvalidation = TRUE
  } else {
    importvalidation = FALSE
  }
  if (file.exists(tarfile)){
    if (import == FALSE){
      system(command = glue::glue("docker load --input {tarfile}"))
      return(tarfile)
    }else if (importvalidation){
      system(command = glue::glue("docker import {tarfile} {imageid}"))
      return(imageid)
    } else {
      message("please input a specific imageid ,which should has no confilct with existed names")
    }
  } else {
    message("tarfile does not exists")
  }
}
