# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' image_rmi
#' Description
#' remove images
#' @param id the image id ,str 
#' @return str
#' 
#' @export
#' @examples
#' image_rmi("frooodle/s-pdf:latest")
image_rmi <- function(id){
    commandline <- glue::glue("docker rmi {id}")
    message(glue::glue("info\\ your command is {commandline},checking the imageids..."))
    allimage <- lsimage()
    if (id %in% c(allimage$REPOSITORY,allimage$`IMAGE ID`)){
      system(commandline)
    }else{
      message("the imageid is not correct")
    }
    return(id)
}
