# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' image_pull
#' Description
#' pull image from dockerhub
#' 
#' @param id the image id ,str
#' @return str
#' 
#' @export
#' @examples
#' image_pull("frooodle/s-pdf:latest")
image_pull <- function(id){
  commandline <- glue::glue("docker pull {id}")
  message(glue::glue("info\\ your command is {commandline},checking the imageids..."))
  allimage <- lsimage()
  if (id %in% allimage$REPOSITORY){
    message("the image already exist")
  }else{
    system(commandline)
  }
  return(id)
}
