# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' image_pull
#' Description
#' pull image from dockerhub
#' 
#' @param id the image id ,str
#' @param use_podman logit, use podman as  backend when it is TRUE
#' @return str
#' 
#' @export
#' @examples
#' image_pull("frooodle/s-pdf:latest")
image_pull <- function(id, use_podman = FALSE){
  commandline <- glue::glue("docker pull {id}")
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},checking the imageids..."))
  allimage <- lsimage(use_podman = use_podman)
  if (id %in% allimage$REPOSITORY){
    message("the image already exist")
  }else{
    system(commandline)
  }
  return(id)
}
