# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Add one to any value
#' 
#' @param base_command A str
#' @param additional A str
#' @param use_podman logit, use podman as  backend when it is TRUE
#'
#' @return data.frame
#' @export
#' @examples
#' lscontainer(additional = "-a")

lscontainer <- function(base_command = "docker ps",
                             additional = "-a", use_podman = FALSE){
  
  if (!is.na(additional)){
    commandline <- glue::glue("{base_command} {additional}")
  } else {
    commandline <- base_command
  }
  
  if (use_podman) {
    commandline = stringr::str_replace(commandline,"docker","podman")
  }
  message(glue::glue("info\\ your command is {commandline},runing..."))
  output <- system(command = commandline,
                   intern = TRUE)
  header <- output[1]
  data_lines <- output[-1]
  data <- do.call(rbind, lapply(data_lines, function(x) {
    strsplit(x, "\\s{2,}")[[1]]
  }))
  header_clean <- strsplit(header, "\\s{2,}")[[1]]
  if (ncol(data) == length(header_clean)) {
    colnames(data) <- header_clean
    data <- as.data.frame(data)
    return(data)
  }else{
    message("something went wrong, check your command")
    return(NA)
  }
}

